name: Build and test

on:
  pull_request:

jobs:
  build-test:
    name: Build docs-gen
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Test docs gen
        run: cd docs-gen && sbt paradox
